# This code is part of Qiskit.
#
# (C) Copyright IBM 2020.
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE.txt file in the root directory
# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.

name: Aqua Unit Tests

on:
  push:
    branches:
      - master
      - 'stable/**'
  pull_request:
    branches:
      - master
      - 'stable/**'

jobs:
  Checks:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [3.7]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Pip cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-checks-${{ hashFiles('setup.py','requirements-dev.txt','constraints.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-checks-
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - uses: ./.github/actions/install-libraries
      - uses: ./.github/actions/install-master-dependencies
        if: ${{ !startsWith(github.ref, 'refs/heads/stable') }}
      - uses: ./.github/actions/install-aqua
      - name: Install Dependencies
        run: |
          sudo apt-get -y install python3-enchant
          sudo apt-get -y install hunspell-en-us
          pip install pyenchant
          pip install cplex
          pip install "cvxpy>1.0.0"
          pip install https://github.com/rpmuller/pyquante2/archive/master.zip
        shell: bash
      - name: Terminate if failure above
        run: exit 1
        if: ${{ !success() }}
        shell: bash
      - run:  pip check
        if: ${{ !cancelled() }}
        shell: bash
      - run:  make copyright
        if: ${{ !cancelled() }}
        shell: bash
      - run:  make spell
        if: ${{ !cancelled() }}
        shell: bash
      - run:  make style
        if: ${{ !cancelled() }}
        shell: bash
      - run:  make lint
        if: ${{ !cancelled() }}
        shell: bash
      - name: Run make lint latest version
        run: |
          pip install -U pylint
          make lint
        if: ${{ !cancelled() }}
        shell: bash
      - name: Run make html
        run:  |
          make html SPHINXOPTS=-W
          cd docs/_build/html
          mkdir artifacts
          tar -zcvf artifacts/documentation.tar.gz --exclude=./artifacts .
        if: ${{ !cancelled() }}
        shell: bash
      - name: Run upload documentation
        uses: actions/upload-artifact@v2
        with:
          name: documentation
          path: docs/_build/html/artifacts/documentation.tar.gz
        if: ${{ !cancelled() }}
      - run:  make doctest
        if: ${{ !cancelled() }}
        shell: bash
  Lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Pip cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-lint-${{ hashFiles('setup.py','requirements-dev.txt','constraints.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-lint-
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - uses: ./.github/actions/install-libraries
      - uses: ./.github/actions/install-master-dependencies
        if: ${{ !startsWith(github.ref, 'refs/heads/stable') }}
      - uses: ./.github/actions/install-aqua
      - name: Install Dependencies
        run: |
          pip install "cvxpy>1.0.0"
          pip install https://github.com/rpmuller/pyquante2/archive/master.zip
      - name: Terminate if failure above
        run: exit 1
        if: ${{ !success() }}
        shell: bash
      - run: make lint
        if: ${{ !cancelled() }}
        shell: bash
      - name: Run make lint latest version
        run: |
          pip install -U pylint
          make lint
        if: ${{ !cancelled() }}
        shell: bash
  Mypy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Pip cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-mypy-${{ hashFiles('setup.py','requirements-dev.txt','constraints.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-mypy-
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - uses: ./.github/actions/install-libraries
      - uses: ./.github/actions/install-master-dependencies
        if: ${{ !startsWith(github.ref, 'refs/heads/stable') }}
      - uses: ./.github/actions/install-aqua
      - name: Mypy under Python ${{ matrix.python-version }}
        run: |
          pip install cplex
          make mypy
        shell: bash
  Aqua:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Pip cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-${{ matrix.python-version }}-pip-aqua-${{ hashFiles('setup.py','requirements-dev.txt','constraints.txt') }}
          restore-keys: |
            ${{ runner.os }}${{ matrix.python-version }}-pip-aqua-
            ${{ runner.os }}${{ matrix.python-version }}-pip-
            ${{ runner.os }}${{ matrix.python-version }}-
      - uses: ./.github/actions/install-libraries
      - uses: ./.github/actions/install-master-dependencies
        if: ${{ !startsWith(github.ref, 'refs/heads/stable') }}
      - uses: ./.github/actions/install-aqua
      - name: Install Dependencies
        run: |
          pip install "cvxpy>1.0.0"
          pip install scikit-quant
          pip install jax jaxlib
        shell: bash
      - name: Install cplex
        run: pip install cplex
        if: ${{ matrix.python-version == 3.7 }}
        shell: bash
      - name: Aqua Unit Tests under Python ${{ matrix.python-version }}
        uses: ./.github/actions/run-tests
        with:
          domain: aqua
          python-version: ${{ matrix.python-version }}
      - name: Deprecation Messages
        run: |
          mkdir ./a${{ matrix.python-version }}
          python tools/extract_deprecation.py -file out.txt -output ./a${{ matrix.python-version }}/aqua.dep
        shell: bash
      - name: Coverage combine
        run: |
          coverage3 combine
          mv .coverage ./a${{ matrix.python-version }}/aqua.dat
        if: ${{ matrix.python-version == 3.7 }}
        shell: bash
      - uses: actions/upload-artifact@v2
        with:
          name: aqua${{ matrix.python-version }}
          path: ./a${{ matrix.python-version }}/*
  Tutorials:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.8]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Pip cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-${{ matrix.python-version }}-pip-tutorials-${{ hashFiles('setup.py','requirements-dev.txt','constraints.txt') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.python-version }}-pip-tutorials-
            ${{ runner.os }}-${{ matrix.python-version }}-pip-
            ${{ runner.os }}-${{ matrix.python-version }}-
      - uses: ./.github/actions/install-libraries
      - uses: ./.github/actions/install-master-dependencies
        if: ${{ !startsWith(github.ref, 'refs/heads/stable') }}
      - uses: ./.github/actions/install-aqua
      - name: Install cplex
        run: pip install cplex
        if: ${{ matrix.python-version == 3.6 }}
        shell: bash
      - name: Install Dependencies
        run: |
          sudo apt-get -y install libgfortran5
          pip install https://github.com/rpmuller/pyquante2/archive/master.zip
          pip install pyscf
          pip install "cvxpy>1.0.0"
          pip install -U jupyter sphinx nbsphinx sphinx_rtd_theme 'matplotlib<3.3.0' qiskit-terra[visualization] cvxpy
          sudo apt-get install -y pandoc graphviz
        shell: bash
      - name: Run Aqua Tutorials
        env:
          OPENBLAS_NUM_THREADS: 1
        run: |
          git clone https://github.com/Qiskit/qiskit-tutorials
          cd qiskit-tutorials
          rm -r tutorials/circuits/
          rm -r tutorials/circuits_advanced/
          rm -r tutorials/noise/
          rm -r tutorials/pulse/
          rm -r tutorials/simulators/
          sphinx-build -b html . _build/html
          cd _build/html
          mkdir artifacts
          tar -zcvf artifacts/tutorials.tar.gz --exclude=./artifacts .
        shell: bash
      - name: Run upload tutorials
        uses: actions/upload-artifact@v2
        with:
          name: tutorials${{ matrix.python-version }}
          path: ./qiskit-tutorials/_build/html/artifacts/tutorials.tar.gz
  Deprecation_Messages_and_Coverage:
    needs: [Checks, Lint, Mypy, Aqua, Tutorials]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Pip cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-coverage-${{ hashFiles('setup.py','requirements-dev.txt','constraints.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-coverage-
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - uses: actions/download-artifact@v2
        with:
          name: aqua3.7
          path: /tmp/a37
      - uses: actions/download-artifact@v2
        with:
          name: aqua3.8
          path: /tmp/a38
      - name: Install Dependencies
        run: pip install -U coverage coveralls diff-cover
        shell: bash
      - name: Combined Deprecation Messages
        run: |
          sort -f -u /tmp/a37/aqua.dep /tmp/a38/aqua.dep || true
        shell: bash
      - name: Coverage combine
        run: coverage3 combine /tmp/a37/aqua.dat
        shell: bash
      - name: Upload to Coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: coveralls || true
        shell: bash
