# This code is part of Qiskit.
#
# (C) Copyright IBM 2020.
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE.txt file in the root directory
# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.

name: Aqua Unit Tests

on:
  push:
    branches:
      - master
      - 'stable/**'
  pull_request:
    branches:
      - master
      - 'stable/**'

jobs:
  Aqua:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Pip cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-${{ matrix.python-version }}-pip-aqua-${{ hashFiles('setup.py','requirements-dev.txt','constraints.txt') }}
          restore-keys: |
            ${{ runner.os }}${{ matrix.python-version }}-pip-aqua-
            ${{ runner.os }}${{ matrix.python-version }}-pip-
            ${{ runner.os }}${{ matrix.python-version }}-
      - uses: ./.github/actions/install-libraries
      - uses: ./.github/actions/install-master-dependencies
        if: ${{ !startsWith(github.ref, 'refs/heads/stable') }}
      - uses: ./.github/actions/install-aqua
      - name: Install Dependencies
        run: |
          pip install "cvxpy>1.0.0"
          pip install scikit-quant
          pip install jax jaxlib
        shell: bash
      - name: Install cplex
        run: pip install cplex
        if: ${{ matrix.python-version == 3.7 }}
        shell: bash
      - name: Aqua Unit Tests under Python ${{ matrix.python-version }}
        uses: ./.github/actions/run-tests
        with:
          domain: aqua
          python-version: ${{ matrix.python-version }}
      - name: Deprecation Messages
        run: |
          mkdir ./a${{ matrix.python-version }}
          python tools/extract_deprecation.py -file out.txt -output ./a${{ matrix.python-version }}/aqua.dep
        shell: bash
      - name: Coverage combine
        run: |
          coverage3 combine
          mv .coverage ./a${{ matrix.python-version }}/aqua.dat
        if: ${{ matrix.python-version == 3.7 }}
        shell: bash
      - uses: actions/upload-artifact@v2
        with:
          name: aqua${{ matrix.python-version }}
          path: ./a${{ matrix.python-version }}/*
  Deprecation_Messages_and_Coverage:
    needs: [Aqua]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Pip cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-coverage-${{ hashFiles('setup.py','requirements-dev.txt','constraints.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-coverage-
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - uses: actions/download-artifact@v2
        with:
          name: aqua3.7
          path: /tmp/a37
      - uses: actions/download-artifact@v2
        with:
          name: aqua3.8
          path: /tmp/a38
      - name: Install Dependencies
        run: pip install -U coverage coveralls diff-cover
        shell: bash
      - name: Combined Deprecation Messages
        run: |
          sort -f -u /tmp/a37/aqua.dep /tmp/a38/aqua.dep || true
        shell: bash
      - name: Coverage combine
        run: coverage3 combine /tmp/a37/aqua.dat
        shell: bash
      - name: Upload to Coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: coveralls || true
        shell: bash
