# This code is part of Qiskit.
#
# (C) Copyright IBM 2020, 2021.
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE.txt file in the root directory
# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.

name: Aqua Unit Tests

on:
  push:
    branches:
      - master
      - 'stable/**'
  pull_request:
    branches:
      - master
      - 'stable/**'

jobs:
  Chemistry:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: ./.github/actions/install-psi4
        if: ${{ matrix.python-version == 3.7 }}
      - uses: ./.github/actions/install-libraries
      - uses: ./.github/actions/install-master-dependencies
        if: ${{ !startsWith(github.ref, 'refs/heads/stable') }}
      - uses: ./.github/actions/install-aqua
      - name: Install Dependencies
        run: |
          if [ -f "$HOME/miniconda/etc/profile.d/conda.sh" ]; then
            source "$HOME/miniconda/etc/profile.d/conda.sh"
            conda activate
            pip install https://github.com/rpmuller/pyquante2/archive/master.zip
          fi
        shell: bash
      - name: Chemistry Unit Tests under Python ${{ matrix.python-version }}
        uses: ./.github/actions/run-tests
        with:
          domain: chemistry
          python-version: ${{ matrix.python-version }}
      - name: Deprecation Messages
        run: |
          mkdir ./c${{ matrix.python-version }}
          python tools/extract_deprecation.py -file out.txt -output ./c${{ matrix.python-version }}/chem.dep
        shell: bash
      - name: Coverage combine
        run: |
          if [ -f "$HOME/miniconda/etc/profile.d/conda.sh" ]; then
            source "$HOME/miniconda/etc/profile.d/conda.sh"
            conda activate
          fi
          coverage3 combine
          mv .coverage ./c${{ matrix.python-version }}/chem.dat
        if: ${{ matrix.python-version == 3.7 }}
        shell: bash
      - uses: actions/upload-artifact@v2
        with:
          name: chemistry${{ matrix.python-version }}
          path: ./c${{ matrix.python-version }}/*
